title: Hongkai Zhang
description: Play with th world.
url: "https://zhk800.github.io"
baseurl: ""

author:
  name: Hongkai Zhang
  email: hongkaiz418@gmail.com
  github: zhk800
  zhihu: prop-39

permalink: /blog/:year/:month/:day/:title/

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
